// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/account/proto/account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Created              string   `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,6,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36848fb0b6d28e2, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *User) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36848fb0b6d28e2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36848fb0b6d28e2, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36848fb0b6d28e2, []int{3}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*Response)(nil), "account.Response")
	proto.RegisterType((*Error)(nil), "account.Error")
	proto.RegisterType((*Token)(nil), "account.Token")
}

func init() {
	proto.RegisterFile("srv/account/proto/account/account.proto", fileDescriptor_f36848fb0b6d28e2)
}

var fileDescriptor_f36848fb0b6d28e2 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbd, 0x6e, 0xe2, 0x40,
	0x10, 0xc7, 0xb1, 0xb1, 0x0d, 0x0c, 0x02, 0xe9, 0x46, 0x57, 0x58, 0x54, 0x3e, 0x17, 0x07, 0x27,
	0x21, 0xd0, 0x41, 0x9d, 0x02, 0x45, 0x51, 0x7a, 0x2b, 0xa4, 0xdf, 0x78, 0x47, 0x8a, 0x15, 0xf0,
	0x5a, 0xbb, 0x6b, 0xf2, 0x1a, 0x79, 0xd0, 0x3c, 0x44, 0xb4, 0x63, 0xe3, 0x24, 0xa4, 0xa1, 0xf2,
	0xfe, 0x3f, 0x46, 0x9a, 0xdf, 0xc8, 0x30, 0x37, 0xfa, 0xb4, 0x16, 0x79, 0xae, 0xea, 0xd2, 0xae,
	0x2b, 0xad, 0xac, 0xea, 0x54, 0xfb, 0x5d, 0xb1, 0x8b, 0x83, 0x56, 0xa6, 0x6f, 0x1e, 0x04, 0x7b,
	0x43, 0x1a, 0xa7, 0xe0, 0x17, 0x32, 0xf6, 0x12, 0x6f, 0x11, 0x66, 0x7e, 0x21, 0x11, 0x21, 0x28,
	0xc5, 0x91, 0x62, 0x3f, 0xf1, 0x16, 0xa3, 0x8c, 0xdf, 0xf8, 0x1b, 0x42, 0x3a, 0x8a, 0xe2, 0x10,
	0xf7, 0xd9, 0x6c, 0x04, 0xce, 0x60, 0x58, 0x09, 0x63, 0x5e, 0x95, 0x96, 0x71, 0xc0, 0x41, 0xa7,
	0x31, 0x86, 0x41, 0xae, 0x49, 0x58, 0x92, 0x71, 0xc8, 0xd1, 0x59, 0xba, 0xa4, 0xae, 0x24, 0x27,
	0x51, 0x93, 0xb4, 0x32, 0xdd, 0xc3, 0x30, 0x23, 0x53, 0xa9, 0xd2, 0x10, 0xfe, 0x81, 0xa0, 0x36,
	0xa4, 0x79, 0xaf, 0xf1, 0x66, 0xb2, 0x3a, 0x53, 0xb8, 0x95, 0x33, 0x8e, 0xf0, 0x2f, 0x44, 0xa4,
	0xb5, 0xd2, 0x26, 0xf6, 0x93, 0xfe, 0x62, 0xbc, 0x99, 0x76, 0xa5, 0x3b, 0x67, 0x67, 0x6d, 0x9a,
	0xde, 0x40, 0xc8, 0x86, 0x23, 0xcb, 0x95, 0xa4, 0x96, 0x95, 0xdf, 0x98, 0xc0, 0x58, 0x92, 0xc9,
	0x75, 0x51, 0xd9, 0x42, 0x95, 0x2d, 0xf4, 0x57, 0x2b, 0xdd, 0x42, 0xf8, 0xa0, 0x5e, 0xa8, 0x74,
	0x47, 0xb0, 0xee, 0xc1, 0xf3, 0xa3, 0xac, 0x11, 0xce, 0x3d, 0x89, 0x43, 0x21, 0x79, 0x74, 0x98,
	0x35, 0x62, 0xf3, 0xee, 0xc1, 0x60, 0xd7, 0x6c, 0x83, 0x4b, 0x88, 0x6e, 0x99, 0x1d, 0xbf, 0x63,
	0xcc, 0x7e, 0x75, 0xf2, 0x8c, 0x9d, 0xf6, 0xf0, 0x1f, 0xf4, 0xef, 0xc9, 0x5e, 0x55, 0x5d, 0x42,
	0xb4, 0xe7, 0xd3, 0x5d, 0xd5, 0x9e, 0x43, 0xb0, 0xab, 0xed, 0xf3, 0x65, 0xf7, 0xf3, 0x6a, 0x4c,
	0x99, 0xf6, 0xf0, 0x3f, 0x4c, 0x1e, 0x1d, 0x84, 0xb0, 0xd4, 0x80, 0x5f, 0x54, 0x7e, 0x8e, 0x3c,
	0x45, 0xfc, 0x73, 0x6d, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x41, 0x6b, 0x59, 0x87, 0x02,
	0x00, 0x00,
}
